# Generated by Django 2.2.7 on 2021-04-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='material_requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mr_parameter', models.CharField(max_length=50)),
                ('mr_entity_name', models.CharField(max_length=50)),
            ],
        ),
    ]
