# Generated by Django 2.2.7 on 2021-07-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gantt_item_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itmcode', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=100)),
                ('station_no', models.CharField(max_length=100)),
                ('temp_id', models.IntegerField(default=None)),
                ('duration', models.CharField(max_length=100)),
                ('date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='gantt_line1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=100)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('planned', models.IntegerField()),
                ('stn_line', models.CharField(default=None, max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='gantt_line_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=100)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('planned', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='production_done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
