# Generated by Django 2.2.7 on 2021-04-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppfapp', '0002_material_requisition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='decoration1',
            new_name='d1',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='decoration2',
            new_name='d2',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='decoration3',
            new_name='d3',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='decoration4',
            new_name='d4',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='decoration5',
            new_name='d5',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='decoration6',
            new_name='d6',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='finishing1',
            new_name='f1',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='finishing2',
            new_name='f2',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='finishing3',
            new_name='f3',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='finishing4',
            new_name='f4',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='finishing5',
            new_name='f5',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='finishing6',
            new_name='f6',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='layer1',
            new_name='l1',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='layer2',
            new_name='l2',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='layer3',
            new_name='l3',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='layer4',
            new_name='l4',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='layer5',
            new_name='l5',
        ),
        migrations.RenameField(
            model_name='item_master_copy',
            old_name='layer6',
            new_name='l6',
        ),
    ]
