# Generated by Django 2.2.7 on 2021-07-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppfapp', '0002_gantt_item_master_gantt_line1_gantt_line_status_production_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='gantt_lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stn_line', models.CharField(max_length=100)),
                ('starttime', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
