# Generated by Django 2.2.7 on 2021-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppfapp', '0003_gantt_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_done',
            name='station_no',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
