# Generated by Django 2.2.7 on 2021-04-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppfapp', '0004_auto_20210409_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_master',
            name='coupli_or_board_size',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='coupli_or_board_size',
            field=models.CharField(max_length=200),
        ),
    ]
