# Generated by Django 2.2.7 on 2021-07-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppfapp', '0004_production_done_station_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_done',
            name='itemname',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
