# Generated by Django 3.2.3 on 2021-05-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppfapp', '0005_auto_20210427_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='mrp_linewise_bms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyf', models.CharField(max_length=100)),
                ('station_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='mrp_linewise_sponge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponge_type', models.CharField(max_length=100)),
                ('sponge_shape', models.CharField(max_length=100)),
                ('station_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='mrp_linewise_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupli_board', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=100)),
                ('station_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='item_master',
            name='d1_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='d2_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='d3_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='d4_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='d5_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='d6_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='f1_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='f2_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='f3_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='f4_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='f5_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='f6_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='l1_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='l2_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='l3_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='l4_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='l5_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master',
            name='l6_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='d1_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='d2_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='d3_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='d4_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='d5_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='d6_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='f1_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='f2_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='f3_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='f4_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='f5_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='f6_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='l1_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='l2_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='l3_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='l4_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='l5_qty',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_master_copy',
            name='l6_qty',
            field=models.FloatField(max_length=50),
        ),
    ]
